### ISSUE TITLE
Missing reactome server version & invalid dependency in Main.java

### ISSUE THREAD

**Issue by cookersjs** [reactome/data-export#1]
When attempting to build the jar file for data-export for release 71, I ran into two seperate issues.

**pom.xml** --> <graph.core.version>1.1.21-SNAPSHOT</graph.core.version> had to be changed to 1.1.20-SNAPSHOT since v1.1.21 wasn't available (https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-snapshots/org/reactome/server/graph/graph-core/)

**src.main.java.org.reactome.server.export.Main** --> I had to comment out [this line](https://github.com/reactome/data-export/blob/master/src/main/java/org/reactome/server/export/Main.java#L4) since I couldn't find this dependency anywhere and it was preventing the jar from building

**Comment by gsviteri** [comment]
Right, that should be ok by now. We will make sure all the versions are deployed in Remote Repos when we commit new changes. Thanks @cookersjs.
